### ISSUE TITLE
ImageMountFailed

### ISSUE THREAD

**Issue by pill64** [osy/Jitterbug#13]
Why did I always have such an error prompt for opening the software for the first time? My device installs the system of Jitterbug's iPhone running ios 14.6, and uses Jit permission ipad os14.6.

**Comment by pill64** [comment]
![Uploading 1FC35D52-590C-4B10-A3D8-2DC7E83B8E31.jpeg…]()

**Comment by pill64** [comment]
![Uploading A494FA38-E9BD-4863-9B75-734579A19F94.jpeg…]()

**Comment by pill64** [comment]
![7B3A0C3C-F6D4-45B6-B218-3EE4BBAE3243](https://user-images.githubusercontent.com/71247770/121856581-3a45be80-cd27-11eb-9f34-474aac495599.jpeg)

**Comment by pill64** [comment]
jitterbug version is 1.1.0

**Comment by osy** [comment]
Please read the readme. This exact issue is listed under troubleshooting.
