### ISSUE TITLE
Using already existing VPN protocols for Self-launching

### ISSUE THREAD

**Issue by bela333** [osy/Jitterbug#14]
Hi! I was wondering if it would be possible to use an already existing VPN protocol (like OpenVPN or WireGuard) so that the device can debug itself through an already existing app, without Jitterbug needing the "Network Extensions" entitlement.

**Comment by osy** [comment]
Sure it’s possible but you have to host your own “reflector” VPN server.

**Comment by bela333** [comment]
Sorry, What I meant was reimplementing a basic VPN server for iOS and integrating the debug functionality into that.

**Comment by osy** [comment]
Then you still need the entitlements…

**Comment by bela333** [comment]
I'm not really familiar with iOS development. Is there something preventing user-signed apps from listening or are VPN apps unable to connect to a server running on the same device?

**Comment by osy** [comment]
This really isn’t the right place to have this discussion.
