### ISSUE TITLE
iOS 15?

### ISSUE THREAD

**Issue by coreycusick** [osy/Jitterbug#18]
It seems to connect to VPN ok.  But does not Mount support files. I’ve tried the iOS 15 support files as well, still won’t mount

**Comment by osy** [comment]
Are you asking if Jitterbug runs on iOS 15 or if it can launch apps on another device running iOS 15?

**Comment by coreycusick** [comment]
I figured it out. Had to rebuild using a beta version of Xcode and update libraries. Works fine now.
