### ISSUE TITLE
Could not find matching provisioning profile

### ISSUE THREAD

**Issue by Symplicityy** [osy/Jitterbug#19]
This is the same as issue #15 but the person who created that issue closed it with no context. I'm having the same issue where I get this error when signing it with AltStore using my developer account.

**Comment by osy** [comment]
From the release notes

> Free developer account users (including AltStore users) should use v1.0.2 for now as the IPA has the Network Extensions entitlements.

**Comment by osy** [comment]
Right but you cannot use AltStore. Sorry that's not clear I'll change it in the next release. (including AltStore users) means ALL altstore users not just free developer account users.

**Comment by Symplicityy** [comment]
Ok that's fine. Thanks for clarifying. Last night I managed to get it installed by compiling it with Xcode but it was late and I never got to reply with the outcome. Sideloadly worked but I was unable to use the VPN tunnel. The only way I got it fully working was Xcode. At least it works. Thanks, sorry to bother you.

**Comment by Symplicityy** [comment]
> Anyways someone managed to get Jitterbug onto TestFlight, so until that's taken down, it'll probably be the best way forward.

Wait really? What the... wow. That's really cool.
