### ISSUE TITLE
App Crashes when trying to delete a support file.

### ISSUE THREAD

**Issue by TechnoKyle27** [osy/Jitterbug#20]
Here is a video showing it happening to me. I am on an iPhone 12 Pro. I have iOS 14.6. https://imgur.com/a/BRRWreA

**Comment by osy** [comment]
Can you get a crash report?

> To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.

**Comment by TechnoKyle27** [comment]
Here is the link to the file:
https://we.tl/t-TCE0qa46gf
