### ISSUE TITLE
Bug with shortcuts on iPad

### ISSUE THREAD

**Issue by Symplicityy** [osy/Jitterbug#21]
I created a shortcut on my 12.9 inch M1 iPad Pro on iOS 14.5 but upon opening the shortcut it gets stuck on the "Select a device." screen. It unfreezes and continues to work as expected when clicking the "< Devices" button in the top left. I've attached a video of what happens when I open the shortcut. https://user-images.githubusercontent.com/17555839/129425897-5c847bb2-9287-452c-86ef-68a9110a4167.MOV

**Comment by osy** [comment]
Does the same issue happen if you are in landscape mode?

**Comment by Symplicityy** [comment]
> Does the same issue happen if you are in landscape mode?

I'm very sorry I didn't reply. I haven't been feeling good lately. I'm assuming you already fixed this but no, the issue doesn't happen in landscape mode.
