### ISSUE TITLE
Click the pop-up window that appears when pairing：faile to communicate with device......

### ISSUE THREAD

**Issue by CD-D** [osy/Jitterbug#25]
Problems that occur when everything is configured normally

**Comment by osy** [comment]
Not sure there's anything I can do about it without any more information.

**Comment by CD-D** [comment]
Under what circumstances will it be impossible to connect?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "osy/Jitterbug"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月6日(星期一) 凌晨2:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [osy/Jitterbug] Click the pop-up window that appears when pairing：faile to communicate with device...... (#25)





 
Not sure there's anything I can do about it without any more information.
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by osy** [comment]
Closing due to insufficient information.
