### ISSUE TITLE
Can’t Install / not working on iphone6 / IOS 12.5.5? 

### ISSUE THREAD

**Issue by Kickflipkid687** [osy/Jitterbug#33]
I tried to install in a few different ways. But it either wouldn’t fully Install with the lite version. Or it would install but when I tried to open it would crash.  

I did finally get 1 error message , that seemed like it’s not supported on my IOS version?

**Comment by conath** [comment]
Correct Jitterbug doesn't work on iOS 12. You should be able to use JIT apps without workaround IIRC.
