### ISSUE TITLE
jitterbugpair not generating mobiledevicepairing/Untrusted Developer

### ISSUE THREAD

**Issue by vebberim** [osy/Jitterbug#37]
I followed the instructions up until using jitterbugpair on my device, this brings up a pop-up on device to Trust This PC. After selecting trust, the UDID.mobiledevicepairing file does not generate. Running the .exe again does nothing. Clicking on the Jitterbug app on device brings a popup stating Untrusted Developer.

Where do I go from here?

**Comment by conath** [comment]
The "trust this computer" enables USB access from the PC to your device. To trust the developer you need to go to Settings app => General => Profiles (?) and trust your app / developer certificate there.
