### ISSUE TITLE
I get "resolving 64:0b:d7:74:9b:e2:@fe80::660b:d7ff:fe74:9be2 failed with the error domain 10, code -72007" when I try to pair my iPhone 6s plus 14.7.1 with an iPhone 15.2

### ISSUE THREAD

**Issue by TheBigChef** [osy/Jitterbug#39]

**Comment by osy** [comment]
The error is `NSNetServicesTimeoutError`. There is an issue in your router/network connection such that the two devices cannot communicate. You can try connecting to another network or using wifi tethering.
