### ISSUE TITLE
[Question] Is disk image and iOS version have to be the same

### ISSUE THREAD

**Issue by js-john** [osy/Jitterbug#4]
In readme.md
"Go here and download the ZIP corresponding to the closest iOS version to the target device. Unzip the download and you should get DeveloperDiskImage.dmg and DeveloperDiskImage.dmg.signature."

I installed Jitterbug app on iPhone with iOS 14.6 and try to start the UTM app on iPad with iOS 14.6. An error was reported: Unable to mount
The latest disk image version available is iOS 14.5

**Comment by jankais3r** [comment]
I do not think the version mismatch is the cause of your problem. I was able to mount 14.5 DeveloperDiskImage on iPadOS 14.6. If you want to be sure, though, you can get 14.6 disk image from [here](https://github.com/xushuduo/Xcode-iOS-Developer-Disk-Image/pull/32/files).

**Comment by Spidy123222** [comment]
> In readme.md
> "Go here and download the ZIP corresponding to the closest iOS version to the target device. Unzip the download and you should get DeveloperDiskImage.dmg and DeveloperDiskImage.dmg.signature."
> 
> I installed Jitterbug app on iPhone with iOS 14.6 and try to start the UTM app on iPad with iOS 14.6. An error was reported: Unable to mount
> The latest disk image version available is iOS 14.5

In most cases it has to match but not every version of ios updates the DMG so that's why for example 14.5 dmg works on 14.6. there are cases like 14.4 dmg works on the increment changes also.

**Comment by flhs0606** [comment]
I have the same issue. But I can open the app in this way:
1.Close utm and jitterbug.
2.Open jitterbug on iphone, launch utm via jitterbug.
3.Utm will automatically start on ipad, but vm will crash if you open it.
4.Reopen utm on ipad, it will show warning message, just ignore.
5.launch utm via jitterbug on iphone.
6.Start vm via utm on ipad, it works!

**Comment by js-john** [comment]
Problem solved
