### ISSUE TITLE
Jitterbug

### ISSUE THREAD

**Issue by hzieechen** [osy/Jitterbug#40]
UTM已经通过Altstore安装完毕，使用的是付费开发者账号签名。安装Jitterbug时出现Non-developer Apple IDs are limited to creating 10 App IDs per week.错误。我确认是用付费开发者账号

**Comment by osy** [comment]
This is an Altstore bug, please check out https://github.com/rileytestut/AltStore

**Comment by hzieechen** [comment]
如果我用mac os版本的Altserver能解决这个问题吗？

**Comment by osy** [comment]
Not a question for me. I don't know much about Altstore/Altserver.
