### ISSUE TITLE
Jitterbug doesn’t seem to be enabling JIT for UTM on iPad OS15.4

### ISSUE THREAD

**Issue by SugarRayLua** [osy/Jitterbug#42]
Has anyone been able to get Jitterbug to enable JIT and open UTM on iPad with iPad OS15.4? Worked fine till upgraded to OS15.4 now won’t mount either with VPN tunnel on same device or tethered device via Wifi. 

I downloaded and installed the new DeveloperDiskImages for OS15.4 from Xcode 13.3 beta 1 and still will not work.

Hopefully someone else has gotten to work.

Thanks!

**Comment by SugarRayLua** [comment]
Tried using DeveloperDiskImages from new Xcode 13.3 beta 2 releases and still doesn't seem to enable JIT to run UTM (finds UTM app when tethered on wifi but won't mount).

**Comment by SugarRayLua** [comment]
Correction: I meant I can't get jitterbug to work after upgrade to iPad OS 15.3.1 (not 15.4)

Thanks.

**Comment by SugarRayLua** [comment]
I got Jitterbug to work on new iPad OS 15.4 release via tethering to another iPad. However, VPN tunnel doesn’t seem to work.

**Comment by sdgros01** [comment]
Any updates on getting the local device VPN permissions set back up to work and function on 15.4?

**Comment by ruthloose88** [comment]
@SugarRayLua Which version of DeveloperDiskImage ended up working for you? 15.4?

**Comment by sdgros01** [comment]
> @SugarRayLua Which version of DeveloperDiskImage ended up working for you? 15.4?

Im interested as well because ive tried a few and still cant get any of it to successfully work anymore

**Comment by SugarRayLua** [comment]
PS, @sdgros01 and @ruthloose88,
I also downloaded newest iPad OS today (14.5.1) and can confirm that the DeveloperDiskImage I previously extracted from the official Xcode 13.3 release still works in Jitterbug for this latest iPad OS update.

Fyi.

**Comment by osy** [comment]
@SugarRayLua have you tried re-creating the pairing? I just confirmed that VPN is working fine for me with 15.4 DMG on latest iOS.

**Comment by SugarRayLua** [comment]
Thanks for checking, @osy, and I apologize, it is working now. One thing I had forgotten from before is that the VPN tunnel only works for me when I’m on wifi; it never has worked when my iPad Pro is connected to its built in Verizon 5G network (which I suspect if due to Verizon blocking the VPN tunnel somehow). I thought I had double checked multiple times that I was on wifi when I first submitted the issue but perhaps I did not and will make extra sure to do so if I encounter the same problem in the future. PS, I’m on your next to your last UTM iOS update and it is working great! Please consider the issue closed.

**Comment by osy** [comment]
Okay, I clarified in the release notes that Cellular is NOT supported. It is a kernel imposed security limitation.

**Comment by SugarRayLua** [comment]
Thanks again, @osy!
