### ISSUE TITLE
Cannot get the pairing key to work

### ISSUE THREAD

**Issue by ansinerd** [osy/Jitterbug#45]
I am using mac os and trying to pair my iPhone 13 ios 15.2 with my secondary device iPad pro 2020 15.1. Using developer disk image 15.0 
Opened command terminal in mac os,
It generated the key
I copied the text from terminal and saved it as it is and airdropped to my iPhone, it opened it in jitterbug but when I try to pair my iPad the app crashes immediately. 2 days I have spent but cannot get it working. Any help?

**Comment by osy** [comment]
> I copied the text from terminal and saved it

Are you saying you saved the text string `SUCCESS: wrote to xxxxxx.mobiledevicepairing` and tried to load that? That is wrong. You need to AirDrop the generated file "xxxxxx.mobiledevicepairing" (the name differs for each device).
