### ISSUE TITLE
1.2.0 Failed to communicate with device.

### ISSUE THREAD

**Issue by Never2333** [osy/Jitterbug#49]
1.2.0  Jitterbug Lite, installed by altstore.

Tried and repaired many times, but still the same message:
Failed to communicate with device. Make sure the device is connected and unlocked and that the pairing is valid.

I used it on one device and want to run UTM.

Please, help me.

**Comment by Mcrich23** [comment]
Same

**Comment by osy** [comment]
From the release notes

> Jitterbug Lite is the same app without any of the VPN features which require special entitlements only available to paid Apple Developer accounts.

Lite will NOT work with one device.
