### ISSUE TITLE
Network Entitlement Extension 

### ISSUE THREAD

**Issue by Poochy1130** [osy/Jitterbug#53]
![29566717-2D6E-411E-A227-A9BA33877DC2](https://user-images.githubusercontent.com/106034685/169713670-e72e75c0-6665-41dd-a0cb-4baad6c1b03b.png)

I have a paid developer account threw udid registrations and when I sign the app with ipa signer or the signulous app im unable to use the vpn tunnel feature with Jitterbug and according to the screenshot when I signed the jitterbug IPA the network entitlement extension is included so a little help would be appreciated so I can use JIT with rocket league sideswipe and my ppsspp emulator (I know everyone recommends to use signtools but I'm not competent enough to understand how to use it for jitterbug and don't have access to a Mac Or windows to install altstore and why would I to anyway when I have a signing service) and I really want to use this like so much I literary made a github just to inquire about this issue I'm going threw) also I been going back and forth with udid customer support about the issue with Jitterbug and they send me a email with another entitlement I might need to get this functional I included a screenshot cause your the developer u would know better then anybody if that entitlement they told me was needed or not....
![D13843F3-26DD-4B99-806A-DE12EAF0007C](https://user-images.githubusercontent.com/106034685/169713802-cd0fb8a0-d5b9-4ccf-ad22-95fec3ec60b6.png)

**Comment by Poochy1130** [comment]
![E64DFDB6-3A85-4CA4-A4D4-62AB3FB4A35E](https://user-images.githubusercontent.com/106034685/169714254-db644f82-0d73-4fc4-a192-4e2f7124ada8.jpeg)

**Comment by osy** [comment]
I’m not sure what your screenshot shows but it doesn’t look like it came from jitterbug at all. You need the Network Extensions entitlement selected.

**Comment by Poochy1130** [comment]
Osy that screenshot the first one came from Udid registrations stating that when I signed your app jitterbug with its service the network extensions entitlement was included in the signing of the app... The 3rd screenshot is another entitlement that udid was saying I possibly needed to make the vpn tunnel function but obviously I dont need it cause u just only mentioned the network extensions entitlement

**Comment by osy** [comment]
Look it’s really hard to play this game of telephone. Either 1) use Apple Developer Portal which I understand, or 2) work it out with UDID registrations or have them contact me. It’s hard to debug this indirectly when so many things look incorrect.

**Comment by Poochy1130** [comment]
What's your email so I can give it to them so they can contact you cause I'm sure there's a whole bunch of udid subscribers who would love to use this awesome app in VPN tunnel mode

**Comment by Poochy1130** [comment]
![Uploading 8944AC76-5826-4630-97C3-2E8E7B104DB3.png…]()

**Comment by Poochy1130** [comment]
Udid is looking forward to hearing from you apparently they had other people asking how to sign your app with thier service to be able to enable the vpn tunnel thier contact email is
support@udidregistrations.com
They said put jitterbug developer in the subject osy
