### ISSUE TITLE
Udid registrations 

### ISSUE THREAD

**Issue by Poochy1130** [osy/Jitterbug#54]
U told me to have udid registrations get in contact with u and they willing to talk with you but u never responded back with your email maybe cause u closed the issue so u didn't see it so I'm just going to give u thier email support@udidregistrations.com
so u can be able to contact them so they can properly fix the signing service so jitterbug can be signed correctly and have the vpn tunnel avaliable for udid developers thank you and sorry for making another ticket I just want this issue to get fixed cause udid is saying when Im signing the app the network entitlement is there so they don't know why the vpn tunnel is not working for udid users

**Comment by osy** [comment]
I’ve already emailed them.

**Comment by Poochy1130** [comment]
Thank you Osy
