### ISSUE TITLE
[Feature Request] Allow installing developer-signed IPAs on self

### ISSUE THREAD

**Issue by JJTech0130** [osy/Jitterbug#58]
It would be really cool if Jitterbug could install a pre-develop-signed IPA on the device, allowing for OTA distribution of develop-signed (not ad-hoc) IPAs. This is necessary in order to distribute Dolphin OTA as signing for normal ad-hoc strips the debuggable entitlement.

**Comment by esgie** [comment]
Cool idea, but seems a little out of Jitterbug’s scope (it is intended to run JIT, not sideload apps). However there is a Chinese app which does exactly that and it’s called Esign.
https://esign.yyyue.xyz/
It lets you install signed ipa files directly on (non-jb) device. The entitlements are preserved, even internal VPN for Jitterbug itself works. DolphiniOS is working fine as well, with JIT enabled via Jitterbug.
You may also import your developer cert.p12 and provisioning profile inside that app and SIGN ipas directly on device, too. So you are able to sign and install third party app from scratch without tethering or anything. Works fine, even with iOS16.1 beta (and latest versions include TrollStore support for iOS15 too).

** For a complete oversight, please be aware that neither app is open source so there may be some security issues involved.. for example, both apps read device UDID by installing custom profile, so there is a risk of its leak as it is unknown how that data is processed; there is some kind of agreement at the first run but it’s in Chinese so I wasn’t really able to understand it. fortunately, signing is performed totally offline and you don’t need to enter your Apple account credentials anywhere in the apps! This significantly reduces the risk in my opinion, but I cannot guarantee anything! The choice is up to you **

**Comment by JJTech0130** [comment]
I discovered that this isn’t necessary for my use-case anyway, development signed apps apparently *can* be distributed OTA.
