### ISSUE TITLE
Jitterbug crashes when trying to query apps

### ISSUE THREAD

**Issue by BluDood** [osy/Jitterbug#60]
I have tried this with both methods (VPN and secondary device) and get the same result.

**Devices:** 
iPad Pro M1 11" (VPN)
iPhone 12 (secondary)

**Crash log** (zipped as i was not allowed to upload a .ips file)
[iPad](https://github.com/osy/Jitterbug/files/8917756/Jitterbug-2022-06-16-114331.zip)
[iPhone](https://github.com/osy/Jitterbug/files/8917778/Jitterbug-2022-06-16-114720.zip)

**Comment by BluDood** [comment]
Both are on iOS 16 Developer Beta 1. How the heck did i forget to mention that

**Comment by osy** [comment]
Fixed in https://github.com/osy/Jitterbug/commit/e110cc8afe87c1094c490b91cc47312f7f4da138
