### ISSUE TITLE
m1 ipad 11 inch can’t open vpn tunnel

### ISSUE THREAD

**Issue by ab0880** [osy/Jitterbug#61]
![Uploading IMG_0267.jpeg…]()

**Comment by ab0880** [comment]
my ipados is 15.1, When I tried to turn on the Jitterbug tunnel in Settings, it immediately closed with each click ，but it work perfect in ios14.3 on my iphone

**Comment by osy** [comment]
You don't need to turn on the tunnel in Settings. If it's selected (or if it's the only VPN), the app should automatically connect when you select your local device.

**Comment by ab0880** [comment]
if i turn on the tunnel in jitterbug ，it will alert error like the picture.&nbsp;

发自我的iPhone


------------------ Original ------------------
From: osy ***@***.***&gt;
Date: Mon,Sep 5,2022 9:30 AM
To: osy/Jitterbug ***@***.***&gt;
Cc: ab0880 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [osy/Jitterbug] m1 ipad 11 inch can’t open vpn tunnel (Issue #61)





 
You don't need to turn on the tunnel in Settings. If it's selected (or if it's the only VPN), the app should automatically connect when you select your local device.

**Comment by osy** [comment]
There is no picture attached.

**Comment by ab0880** [comment]
sorry, i forgot it



发自我的iPhone


------------------ Original ------------------
From: osy ***@***.***&gt;
Date: Mon,Sep 5,2022 9:41 AM
To: osy/Jitterbug ***@***.***&gt;
Cc: ab0880 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [osy/Jitterbug] m1 ipad 11 inch can’t open vpn tunnel (Issue #61)





 
There is no picture attached.

**Comment by Xernium** [comment]
If you are trying to use Jitterbug with TrollStore, that doesnt work yet. See https://github.com/opa334/TrollStore/issues/38

**Comment by ab0880** [comment]
I have upgraded trollstorr to 1.06 and it works perfectly now.thanks!



发自我的iPhone


------------------ Original ------------------
From: FivePB (Xer) ***@***.***&gt;
Date: Mon,Sep 5,2022 8:40 PM
To: osy/Jitterbug ***@***.***&gt;
Cc: ab0880 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [osy/Jitterbug] m1 ipad 11 inch can’t open vpn tunnel (Issue #61)





 
If you are trying to use Jitterbug with TrollStore, that doesnt work yet. See opa334/TrollStore#38
