### ISSUE TITLE
Can not query apps installed by trollstore.

### ISSUE THREAD

**Issue by F-Unction** [osy/Jitterbug#62]
Can not query apps installed by trollstore.

**Comment by Alexck002** [comment]
I was going to report this issue too

**Comment by osy** [comment]
I’ve spoken to the dev of trollstore about it. It’s an issue that extends to jitstreamer and Xcode itself. Trollstore installed apps cannot be debugged. Need to find out why.

**Comment by Alexck002** [comment]
I just installed JITstreamer and I can now run Flycast installed with TrollStore ☺️

**Comment by F-Unction** [comment]
It seems apps can enable jit by themselves. Such as PojavLauncher
https://github.com/PojavLauncherTeam/PojavLauncher_iOS
> For iOS 14.0-15.5beta4 on compatible devices, [TrollStore](https://github.com/opa334/TrollStore) is recommended to keep PojavLauncher permanently signed and have JIT automatically enabled.

**Comment by osy** [comment]
Fixed in https://github.com/osy/Jitterbug/commit/e110cc8afe87c1094c490b91cc47312f7f4da138
