### ISSUE TITLE
VPN Tunnel not enabling JIT

### ISSUE THREAD

**Issue by PatFussy69** [osy/Jitterbug#66]
I have signed and installed Jitterbug 1.3.1 using UDID Registrations iOS App Signer, and enabled the local device VPN Tunnel, but it doesnt enable JIT. Ive tried on both UTM and Dolphin. When i go into the app and select my device (13 Pro Max iOS 1.16.02) it pulls up the pairing screen with "no files found". Im not sure what else i need to do, or if did something wrong.

**Comment by PatFussy69** [comment]
I have verified that the ipa has been signed with the correct entitlement(s), but im still not able to get JIT enabled. I have the Local device VPN enabled, and cannot use JIT in DolphiniOS, Pojav, or UTM. In the app i see my local device, and have no pairing files. Am i missing something? Do i need to generate pairing files for my device? 
![image](https://user-images.githubusercontent.com/84402126/206927413-587a7342-a6f6-4f4b-8815-58a7a9bdb714.png)
![image](https://user-images.githubusercontent.com/84402126/206927420-bb89a5ff-fde7-4d44-b18b-533c95de5ec2.png)

**Comment by osy** [comment]
Follow the instructions https://github.com/osy/Jitterbug/releases
