### ISSUE TITLE
Jitterbug crashing after force close

### ISSUE THREAD

**Issue by jawshoeadan** [osy/Jitterbug#7]
Steps to reproduce:
1. Sign with iOS App Signer and paid developer account with network extension entitlements
2. Pair with vpn tunnel loopback to device
3. Force close Jitterbug and reopen
4. Click on either the support files or pairings tabs and app crashes
[Jitterbug-2021-06-10-151227.txt](https://github.com/osy/Jitterbug/files/6634986/Jitterbug-2021-06-10-151227.txt)

**Comment by osy** [comment]
Oh this is iOS 15. Yeah, I never tested on it and it seems like the crash is in SwiftUI.

**Comment by osy** [comment]
@jawshoeadan does this still happen on the latest iOS 15 beta? I can't reproduce it.
